AteshgahPracticalTest/Models/Loan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoanPracticalTest.Models
{
    public class Loan
    {
        public int Id { get; set; }
        
        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }
        
        [Column(TypeName = "decimal(18,2)")]
        public decimal InterestRate { get; set; }
        public int LoanPeriod { get; set; }
        public DateTime PayoutDate { get; set; }

        public int ClientId { get; set; }
        public Client Client { get; set; }

        public ICollection<Invoice> Invoices { get; set; }
    }
}

AteshgahPracticalTest/Controllers/InvoiceController.cs
using System.Threading.Tasks;
using LoanPracticalTest.Data.Repositories;
using LoanPracticalTest.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace LoanPracticalTest.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly ILogger<InvoiceController> _logger;
        private readonly IInvoiceRepository _invoiceRepository;

        public InvoiceController(
            ILogger<InvoiceController> logger,
            IInvoiceRepository invoiceRepository)
        {
            _logger = logger;
            _invoiceRepository = invoiceRepository;
        }
        
        [HttpPost]
        public async Task<JsonResult> CalculateInvoices([FromBody] LoanDetailsViewModel loan)
        {
            var invoices = await _invoiceRepository.CalculateInvoices(loan);

            return Json(invoices);
        }
    }
}

AteshgahPracticalTest/Controllers/LoanController.cs
using System.Linq;
using System.Threading.Tasks;
using LoanPracticalTest.Data.Repositories;
using LoanPracticalTest.Models;
using LoanPracticalTest.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace LoanPracticalTest.Controllers
{
    public class LoanController : Controller
    {
        private readonly ILogger<LoanController> _logger;
        private readonly ILoanRepository _loanRepository;
        private readonly IClientRepository _clientRepository;
        private readonly IInvoiceRepository _invoiceRepository;

        public LoanController(
            ILogger<LoanController> logger,
            ILoanRepository loanRepository,
            IClientRepository clientRepository,
            IInvoiceRepository invoiceRepository)
        {
            _logger = logger;
            _loanRepository = loanRepository;
            _clientRepository = clientRepository;
            _invoiceRepository = invoiceRepository;
        }

        private void LoadClients()
        {
            ViewBag.Clients =  _clientRepository.GetAllClients().Result.Select(c => new SelectListItem
            {
                Text = c.Name + " " + c.Surname,
                Value = c.Id.ToString()
            });
        }

        private void LoadLoanPeriods()
        {
            var loanPeriods = Enumerable.Range(3, 22).ToList();
            
            ViewBag.LoanPeriods = loanPeriods.Select(l => new SelectListItem
            {
                Text = l.ToString(),
                Value = l.ToString()
            });
        }
        
        public async Task<IActionResult> Index()
        {
            var model = await _loanRepository.GetLoanList();

            return View(model);
        }
        
        // GET
        public async Task<IActionResult> Details(int loanId)
        {
            var loanModel = await _loanRepository.GetLoanDetails(loanId);
            loanModel.InvoicesList = await _invoiceRepository.GetLoanInvoices(loanId);

            LoadClients();
            LoadLoanPeriods();

            return View(loanModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            LoadClients();
            LoadLoanPeriods();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(LoanDetailsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var loanModel = new Loan()
                {
                    Amount = model.Amount,
                    InterestRate = model.InterestRate,
                    LoanPeriod = model.LoanPeriod,
                    PayoutDate = model.PayoutDate,
                    ClientId = model.ClientId,
                    Invoices = _invoiceRepository.CalculateInvoices(model).Result.InvoicesList
                };

                var resultModel = await _loanRepository.Add(loanModel);

                return RedirectToAction("Details", new { loanId = resultModel.Id });
            }
            
            _logger.LogError(ModelState.ValidationState.ToString());

            LoadClients();
            LoadLoanPeriods();
            
            return View(model);
        }
    }
}

AteshgahPracticalTest/Views/Loan/Create.cshtml
@model LoanDetailsViewModel

@{
    ViewData["Title"] = "Add New Loan";
}

<h2>@ViewData["Title"]</h2>

<div class="p-5">
    
    <form enctype="multipart/form-data" asp-controller="loan" method="post" class="mt-3">
        <div class="form-group row mb-4">
            <label class="col-sm-3 col-form-label">Client</label>
            <div class="col-sm-9">
                <select asp-for="ClientId" asp-items="@ViewBag.Clients" class="form-control">
                    <option value="">Please select Client</option>
                </select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row mb-4">
            <label asp-for="TelephoneNr" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <input asp-for="TelephoneNr" class="form-control">
                <span asp-validation-for="TelephoneNr" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row mb-4">
            <label asp-for="Amount" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <input asp-for="Amount" id="Amount" name="Amount" class="form-control" type="number" min="100", max="5000">
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row mb-4">
            <label class="col-sm-3 col-form-label">Periods</label>
            <div class="col-sm-9">
                <select asp-for="LoanPeriod" asp-items="@ViewBag.LoanPeriods" id="LoanPeriod" name="LoanPeriod" class="form-control">
                    <option value="">Please select period</option>
                </select>
                <span asp-validation-for="LoanPeriod" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row mb-4">
            <label asp-for="InterestRate" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <input asp-for="InterestRate" id="InterestRate" name="InterestRate" class="form-control">
                <span asp-validation-for="InterestRate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row mb-4">
            <label asp-for="PayoutDate" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <input asp-for="PayoutDate" id="PayoutDate" name="PayoutDate" type="date" class="form-control">
                <span asp-validation-for="PayoutDate" class="text-danger"></span>
            </div>
        </div>

        <div class="d-flex justify-content-end mt-1">
            <button id="calculateInvoices" class="btn btn-primary ml-4">Calculate Invoices</button>
        </div>

        <div id="invoicePart">
            <div class="form-group row">
                <label asp-for="InvoicesList" class="col-sm-4 col-form-label mb-3"></label>
                <div class="col-sm-12">
                    <div class="table-responsive-sm">
                        <table id="tblInvoices" class="table table-bordered">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Invoice No</th>
                                <th scope="col">Due Date</th>
                                <th scope="col">Amount</th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-end mt-3">
                <label class="col-sm-2 col-form-label">Total Interest</label>
                <div class="col-sm-3 p-0">
                    <input id="TotalInterest" name="TotalInterest" value="" class="form-control" readonly>
                </div>
            </div>
            
        </div>
        
        <div class="d-flex justify-content-end mt-4">
            <button type="submit" id="createLoan" class="btn btn-primary ml-4">Create</button>
            <a asp-action="Index" class="btn btn-secondary ml-4">Cancel</a>
        </div>
        
    </form>
    
</div>

@section Scripts {

    <script type="text/javascript">  
    
     $(function () {
         $("#invoicePart").hide();
         $("#createLoan").prop("disabled",true); 
     });
    
    $(function () {  
            $("#calculateInvoices").click(function () {
                var loan = {};  
                loan.Amount = $("#Amount").val();
                loan.LoanPeriod = $("#LoanPeriod").val();
                loan.InterestRate = $("#InterestRate").val();
                loan.PayoutDate = $("#PayoutDate").val();
                if (loan.Amount != "" && loan.LoanPeriod != "" && loan.InterestRate != "" && loan.PayoutDate != "") {
                    $.ajax({  
                        type: "POST",  
                        url: '@Url.Action("CalculateInvoices", "Invoice")',  
                        data: JSON.stringify(loan),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            $("#tblInvoices tbody tr").remove(); 
                            $("#invoicePart").show();
                            $.each(data.invoicesList, function (i, item) {  
                                var rows = "<tr>"  
                                + "<td class='prtoducttd'>" + item.orderNr + "</td>"  
                                + "<td class='prtoducttd'>" + item.invoiceNr + "</td>"  
                                + "<td class='prtoducttd'>" + item.dueDate + "</td>"  
                                + "<td class='prtoducttd'>" + item.amount + "</td>"  
                                + "</tr>";
                                $('#tblInvoices tbody').append(rows);
                            }); 
                            $('#TotalInterest').val(data.totalInterest);
                            $("#createLoan").prop("disabled",false); 
                        },  
                        error: function (ex) {  
                            var r = jQuery.parseJSON(response.responseText);  
                            alert("Message: " + r.Message);  
                            alert("StackTrace: " + r.StackTrace);  
                            alert("ExceptionType: " + r.ExceptionType);  
                        }  
                    });
                }
                return false;  
            });  
        });  
    
    </script>
}

AteshgahPracticalTest/Views/Loan/Details.cshtml
@model LoanDetailsViewModel

@{
    ViewData["Title"] = "Loan Details";
}

<h2>@ViewData["Title"]</h2>

<div class="p-5">
    
    <form enctype="multipart/form-data" class="mt-3">
        <div class="form-group row mb-4">
            <label class="col-sm-3 col-form-label">Client</label>
            <div class="col-sm-9">
                <select asp-for="ClientId" asp-items="@ViewBag.Clients" class="form-control" disabled></select>
            </div>
        </div>
        <div class="form-group row mb-4">
            <label asp-for="TelephoneNr" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <input asp-for="TelephoneNr" class="form-control" readonly>
                <span asp-validation-for="TelephoneNr" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row mb-4">
            <label asp-for="Amount" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <input asp-for="Amount" class="form-control" readonly>
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row mb-4">
            <label class="col-sm-3 col-form-label">Periods</label>
            <div class="col-sm-9">
                <select asp-for="LoanPeriod" asp-items="@ViewBag.LoanPeriods" class="form-control" disabled></select>
            </div>
        </div>
        <div class="form-group row mb-4">
            <label asp-for="InterestRate" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <input asp-for="InterestRate" class="form-control" readonly>
                <span asp-validation-for="InterestRate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row mb-4">
            <label asp-for="PayoutDate" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <input asp-for="PayoutDate" type="date" class="form-control" readonly>
                <span asp-validation-for="PayoutDate" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="InvoicesList" class="col-sm-4 col-form-label mb-3"></label>
            <div class="col-sm-12">
                <div class="table-responsive-sm">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Invoice No</th>
                            <th scope="col">Due Date</th>
                            <th scope="col">Amount</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var invoice in Model.InvoicesList)
                        {
                            <tr>
                                <td>@invoice.OrderNr</td>
                                <td>@invoice.InvoiceNr</td>
                                <td>@invoice.DueDate.ToString("dd/MM/yyyy")</td>
                                <td>@invoice.Amount</td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


        <div class="d-flex justify-content-end mt-4">
            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>

AteshgahPracticalTest/Views/Loan/Index.cshtml
@model IEnumerable<LoansListViewModel>

@{
    ViewData["Title"] = "Loan List";
}

<h2>@ViewData["Title"]</h2>

<div class="p-4">

    <div class="table-responsive-sm">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">ClientId</th>
                <th scope="col">Client</th>
                <th scope="col">Loan Amount</th>
                <th scope="col">Payout Date</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var loan in Model)
            {
                <tr>
                    <td>@loan.ClientId</td>
                    <td>@loan.Client</td>
                    <td>@loan.Amount</td>
                    <td>@loan.PayoutDate.ToString("dd/MM/yyyy")</td>
                    <td>
                        <a asp-route-loanId="@loan.LoanId" asp-controller="Loan" asp-action="Details">Details</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-end mt-5">
        <a asp-controller="Loan" asp-action="Create" class="btn btn-primary ml-4">New</a>
        <a asp-controller="Home" asp-action="ExitApp" class="btn btn-secondary ml-4">Exit</a>
    </div>

</div>